### ISSUE TITLE
ERROR: Service 'service' failed to build : Build failed

### ISSUE THREAD

**Issue by jamalkaksouri** [gbeletti/service-golang#3]
For this project, I am using Windows operating system. When I try to build Docker-compose, I receive an error.
The Docker service runs on my computer.

![error](https://user-images.githubusercontent.com/12379287/192107574-8c94e3a5-fba9-413c-8a15-973ddf88ff79.png)

**Comment by gbeletti** [comment]
Gosec's issue has been resolved.
