### ISSUE TITLE
Won't build

### ISSUE THREAD

**Issue by webcentricds** [gbeletti/service-golang#5]
Getting:

me@mymachine:~/gitDevelopment/Go/service-golang$ go build
main.go:8:2: cannot find package "github.com/gbeletti/service-golang/dbmongo" in any of:
	/usr/local/go/src/github.com/gbeletti/service-golang/dbmongo (from $GOROOT)
	/home/denglish/work/src/github.com/gbeletti/service-golang/dbmongo (from $GOPATH)
main.go:9:2: cannot find package "github.com/gbeletti/service-golang/httpserver" in any of:
	/usr/local/go/src/github.com/gbeletti/service-golang/httpserver (from $GOROOT)
	/home/denglish/work/src/github.com/gbeletti/service-golang/httpserver (from $GOPATH)
main.go:10:2: cannot find package "github.com/gbeletti/service-golang/queuerabbit" in any of:
	/usr/local/go/src/github.com/gbeletti/service-golang/queuerabbit (from $GOROOT)
	/home/denglish/work/src/github.com/gbeletti/service-golang/queuerabbit (from $GOPATH)
main.go:11:2: cannot find package "github.com/gbeletti/service-golang/servicemanager" in any of:
	/usr/local/go/src/github.com/gbeletti/service-golang/servicemanager (from $GOROOT)
	/home/denglish/work/src/github.com/gbeletti/service-golang/servicemanager (from $GOPATH)
main.go:12:2: cannot find package "github.com/joho/godotenv" in any of:
	/usr/local/go/src/github.com/joho/godotenv (from $GOROOT)
	/home/denglish/work/src/github.com/joho/godotenv (from $GOPATH)

when I try to build the project.

**Comment by gbeletti** [comment]
What is your setup? What is your $GOROOT, $GOPATH and go version? Did you run `go mod tidy` before trying to build?
